### ISSUE TITLE
Some SNES consoles require a pull-down resistor in the DATA line

### ISSUE THREAD

**Issue by bootsector** [bootsector/usb2classic#1]
Although it's working fine on several NES consoles, in some SNES consoles it might be necessary a 10K pull-down resistor in the DATA line (INPUT_DATA/IO36).

Reason for this needs further investigation, but adding the 10K pull-down seems to fix the issue.

**Comment by bootsector** [comment]
Pull down resistor seems to fix it.

**Comment by requeijaum** [comment]
Remember to add a switch for that pull down resistor. Murphy's Law...
