### ISSUE TITLE
How would a RJ45 to DB9 (Megadrive) cable be wired ?

### ISSUE THREAD

**Issue by eleriaqueen** [bootsector/usb2classic#2]
Hi, I ordered a usb2classic some time ago and with it a RJ45 -> Super Nintendo cable.
My brother got an Analogue Mega SG (Megadrive FPGA console) for christmas and I would like to use my usb2classic with it, so I'm considering making a cable myself.
Which leads me to the question : How would a RJ45 to DB9 cable be wired ?
Also it would be great if more RJ45 to Retro Consoles pinouts were included in the "Doc" folder. (I only see NES / SNES and Saturn)

Thanks in advance, and thanks for your hard work !

**Comment by bootsector** [comment]
DB9 (Sega Genesis, etc...) and DB15 (NeoGeo and 3DO) cables are simple male-female extension cables. They don't use the RJ45 interface, as there are specific DB9 and DB15 connectors on-board for them.

This is the DB9 extension cable I recommend for connecting USB2Classic to the Mega Sg/Genesis:

https://www.ebay.com/itm/Original-1990-Heavy-Duty-High-Quality-6-Ft-Extension-Cables-Cable-Sega-Genesis/173203942822 (non-affiliated link)
