### ISSUE TITLE
Will Dreamcast support be implemented?

### ISSUE THREAD

**Issue by badass-boss** [bootsector/usb2classic#4]
As the title says- will it be possible to use USB controllers and connect them to Dreamcast with this in the future or maybe even right now?? I'm talking about simple button controllers, support for VMUs isn't needed. Please reply, thanks in advance

**Comment by bootsector** [comment]
There are no plans. You can achieve this with the RetroPad32 plus an USB Input Module and a DC output cable. However the RetroPad32 isn’t open source unfortunately.
